# Generated by Django 3.2 on 2021-04-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_picture',
            field=models.URLField(null=True),
        ),
    ]
